/**
 * Mobile Menu Hamburger Component
 * Handles opening/closing of mobile navigation drawer
 * HTML is generated by includes/mobile-menu.php
 */

(function() {
    'use strict';

    // Initialize mobile menu
    function initMobileMenu() {
        console.log('Mobile menu: Initializing...');

        // Check if drawer exists (should be included via mobile-menu.php)
        const drawer = document.querySelector('.mobile-menu-drawer');
        if (!drawer) {
            console.error('Mobile menu: Drawer not found! Make sure mobile-menu.php is included.');
            return;
        }

        // Check if already initialized
        const header = document.querySelector('.header-content');
        if (!header) {
            console.error('Mobile menu: Header not found!');
            return;
        }

        if (header.querySelector('.mobile-menu-toggle')) {
            console.log('Mobile menu: Already initialized');
            return;
        }

        console.log('Mobile menu: Header found');

        // Create hamburger button
        const hamburgerBtn = document.createElement('button');
        hamburgerBtn.className = 'mobile-menu-toggle';
        hamburgerBtn.setAttribute('aria-label', 'Menú');
        hamburgerBtn.innerHTML = `
            <div class="hamburger">
                <span></span>
                <span></span>
                <span></span>
            </div>
        `;

        // Add button to header
        header.appendChild(hamburgerBtn);
        console.log('Mobile menu: Hamburger button added to header');

        // Setup event listeners
        const overlay = document.querySelector('.mobile-menu-overlay');
        const closeBtn = drawer.querySelector('.mobile-menu-close');

        hamburgerBtn.addEventListener('click', openMenu);
        if (overlay) overlay.addEventListener('click', closeMenu);
        if (closeBtn) closeBtn.addEventListener('click', closeMenu);

        console.log('Mobile menu: Event listeners attached');
        console.log('Mobile menu: Initialization complete!');

        // Close on ESC key
        document.addEventListener('keydown', (e) => {
            if (e.key === 'Escape' && drawer.classList.contains('active')) {
                closeMenu();
            }
        });

        // Update cart count when it changes
        const cartCountElement = document.getElementById('cart-count');
        if (cartCountElement) {
            const observer = new MutationObserver(() => {
                updateCartBadge();
            });

            observer.observe(cartCountElement, {
                childList: true,
                characterData: true,
                subtree: true
            });
        }
    }

    function updateCartBadge() {
        const cartCountElement = document.getElementById('cart-count');
        const drawer = document.querySelector('.mobile-menu-drawer');

        if (!cartCountElement || !drawer) return;

        const newCount = cartCountElement.textContent.trim();
        let badge = drawer.querySelector('.mobile-menu-badge');
        const cartLink = drawer.querySelector('#mobile-cart-link');

        if (!cartLink) return;

        if (newCount !== '0' && newCount !== '') {
            if (!badge) {
                badge = document.createElement('span');
                badge.className = 'mobile-menu-badge';
                cartLink.appendChild(badge);
            }
            badge.textContent = newCount;
        } else if (badge) {
            badge.remove();
        }
    }

    function openMenu() {
        console.log('Mobile menu: Opening menu...');
        const toggle = document.querySelector('.mobile-menu-toggle');
        const overlay = document.querySelector('.mobile-menu-overlay');
        const drawer = document.querySelector('.mobile-menu-drawer');

        if (!toggle || !overlay || !drawer) {
            console.error('Mobile menu: Cannot open - elements not found', { toggle, overlay, drawer });
            return;
        }

        toggle.classList.add('active');
        overlay.classList.add('active');
        drawer.classList.add('active');
        document.body.classList.add('mobile-menu-open');
        console.log('Mobile menu: Menu opened');

        // Trap focus in drawer
        const focusableElements = drawer.querySelectorAll('a, button');
        if (focusableElements.length > 0) {
            focusableElements[0].focus();
        }
    }

    function closeMenu() {
        console.log('Mobile menu: Closing menu...');
        const toggle = document.querySelector('.mobile-menu-toggle');
        const overlay = document.querySelector('.mobile-menu-overlay');
        const drawer = document.querySelector('.mobile-menu-drawer');

        if (!toggle || !overlay || !drawer) {
            console.error('Mobile menu: Cannot close - elements not found');
            return;
        }

        toggle.classList.remove('active');
        overlay.classList.remove('active');
        drawer.classList.remove('active');
        document.body.classList.remove('mobile-menu-open');
        console.log('Mobile menu: Menu closed');
    }

    // Initialize when DOM is ready
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', initMobileMenu);
    } else {
        initMobileMenu();
    }

    // Expose close function globally for external use
    window.closeMobileMenu = closeMenu;
})();
